### ISSUE TITLE
Why not name '+' as Add and '-' as Sub, refer to std::ops::{Add,Sub,Mul,Div}? So all them are 3 letters.

### ISSUE THREAD

**Issue by mhfan** [yds12/mexe#16]
https://github.com/yds12/mexe/blob/c3573891e37fb101ec8eea964c57467000bb2748/src/types.rs#L5

**Comment by yds12** [comment]
It's a good suggestion, thanks. I'll do it, or if you want to open a PR, feel free to (let me know). In this case, I'd keep the constants (character names) as they are, but apply the fix to the `Operator` enum.

**Comment by yds12** [comment]
Done here: https://github.com/yds12/mexe/commit/6438ecf3462cce67c22209116ac046060cecbf24
